### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by Johannes099** [V1li/BleachHack-unofficial#1]
Hey there,
I appreciate that you've done this, but which Fabric loader version, and (if required) which fabric api version did you use, cause my game crashes every time.
Thank you
Johannes

**Comment by vil** [comment]
Hi,

All the fabric version, etc. should be using the latest versions ([see here](https://fabricmc.net/develop/)).

~Vili

**Comment by Johannes099** [comment]
Hey, I tried everything, but everytime i start the game I get the error code 1. I tried to js put your mod in the mod folder, I tried it with your mod and fabric API, I tried it with your mod, the latest bleachhack mod and fabric API, I tried js your mod and the latest bleachhack mod.
Everytime

**Comment by vil** [comment]
Hi,

Send your crash log from `%appdata%\.minecraft\`. It says the actual error message.

**Comment by Johannes099** [comment]
Hey,
Sry for my late respond.
Here is the crash log
[2024-04-16-6.log.gz](https://github.com/vil/BleachHack-unofficial/files/15023238/2024-04-16-6.log.gz)
[latest.log](https://github.com/vil/BleachHack-unofficial/files/15023239/latest.log)
The name of the first log says its from April 16th, but it was created today in my flles
Ty
Johannes

**Comment by vil** [comment]
Hi,

The problem is that you aren't using the latest Java version. You can get it from [here.](https://www.oracle.com/java/technologies/downloads/#jdk22-windows)

**Comment by Johannes099** [comment]
Hey, it was not the problem. I installed the newest version. But still the same

**Comment by vil** [comment]
Hi,

You have to change the Java executable to use the latest Jdk, the one that I told you to install, in the Minecraft launcher settings.

Refer to https://minecrafthopper.net/help/guides/changing-java-version/

**Comment by Johannes099** [comment]
Hey,
 Yes i did, now its working, tysm
Johannes

**Comment by vil** [comment]
No problem.

**Comment by Johannes099** [comment]
I can start now, but i cant activate anything:(
